name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    strategy:
      fail-fast: false
      matrix:
        target: ["android-arm", "android-arm64", "android-x64"]

    steps:
      - uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '14'

      - name: Install prebuild tools
        run: |
          npm install -g node-gyp node-pre-gyp prebuild-install

      - name: Set up Android SDK
        run: |
          wget https://dl.google.com/android/repository/sdk-tools-linux-4333796.zip
          sudo unzip sdk-tools-linux-4333796.zip -d /usr/local/android-sdk
          echo "ANDROID_HOME=/usr/local/android-sdk" >> $GITHUB_ENV
          echo "ANDROID_SDK_ROOT=/usr/local/android-sdk" >> $GITHUB_PATH
          echo "LD_LIBRARY_PATH=/usr/local/android-sdk/emulator/lib64:$LD_LIBRARY_PATH" >> $GITHUB_ENV
          echo "LD_LIBRARY_PATH=/usr/local/android-sdk/platform-tools:$LD_LIBRARY_PATH" >> $GITHUB_ENV

      - name: Install sqlite3 for Android ARM64
        run: |
          npm install sqlite3
          # 使用node-pre-gyp编译sqlite3，指定目标架构为arm64
          node-pre-gyp configure --target_arch=arm64
          node-pre-gyp build --target_arch=arm64

      - name: Upload sqlite3 compiled files as artifact
        uses: actions/upload-artifact@v3
        with:
          name: sqlite3-artifact-arm64
          # 路径可能需要根据实际构建的文件调整
          path: build/Release/sqlite3.node
          if-no-files-found: error
     

      - name: Run a multi-line script
        run: |
          echo Add other actions to test and deploy your Android project.
