name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '14'

      - name: Set up Android SDK
        run: |
          wget https://dl.google.com/android/repository/sdk-tools-linux-4333796.zip
          sudo unzip sdk-tools-linux-4333796.zip -d /usr/local/android-sdk
          echo "ANDROID_HOME=/usr/local/android-sdk" >> $GITHUB_ENV
          echo "ANDROID_SDK_ROOT=/usr/local/android-sdk" >> $GITHUB_ENV
          echo "LD_LIBRARY_PATH=/usr/local/android-sdk/emulator/lib64:$LD_LIBRARY_PATH" >> $GITHUB_ENV
          echo "LD_LIBRARY_PATH=/usr/local/android-sdk/platform-tools:$LD_LIBRARY_PATH" >> $GITHUB_ENV

      - name: Install sqlite3 for Android
        run: |
          npm install prebuild-install
          npm install node-pre-gyp
          # 指定一个目录来存放编译后的sqlite3文件
          npm install sqlite3 --compile --verbose --prefix=/path/to/your/project
          
      - name: Upload sqlite3 compiled files as artifact
        uses: actions/upload-artifact@v3
        with:
          name: sqlite3-artifact
          # 指定上传的文件或文件模式，这里需要根据实际的编译输出路径来确定
          path: /path/to/your/project/node_modules/sqlite3/lib/binding/
          if-no-files-found: error

      - name: Run a multi-line script
        run: |
          echo Add other actions to test and deploy your Android project.
